baseURL = 'https://lanchonete.tllester.info/'
title = 'Lanchonete'

defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = false

[params]
  logo = 'lanchonete.png'

[languages]
  [languages.pt]
    languageCode = 'pt-BR'
    languageName = 'Português'
    weight = 1
    title = 'Lanchonete'
    [languages.pt.params]
      description = 'uma rede consultora e voluntária'
      logo = 'lanchonete.png'
    [[languages.pt.menus.main]]
      identifier = 'about'
      name = 'Sobre'
      url = '/about/'
      weight = 10
    [[languages.pt.menus.main]]
      identifier = 'post'
      name = 'Artigos'
      url = '/posts/'
      weight = 20
    [[languages.pt.menus.main]]
      identifier = 'arquivo'
      name = 'Arquivo'
      url = '/arquivo/'
      weight = 30
    [[languages.pt.menus.main]]
      identifier = 'cidadequeer'
      name = 'Cidade Queer'
      url = '/cidadequeer/'
      weight = 40
    [[languages.pt.menus.main]]
      identifier = 'paim'
      name = 'A Rua Paim'
      url = '/paim/'
      weight = 50

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 2
    title = 'Lanchonete'
    [languages.en.params]
      description = 'a hybrid consultancy and volunteer network'
      logo = 'lanchonete.png'
    [[languages.en.menus.main]]
      identifier = 'about'
      name = 'About'
      url = '/about/'
      weight = 10
    [[languages.en.menus.main]]
      identifier = 'post'
      name = 'Posts'
      url = '/posts/'
      weight = 20
    [[languages.en.menus.main]]
      identifier = 'arquivo'
      name = 'Archive'
      url = '/arquivo/'
      weight = 30
    [[languages.en.menus.main]]
      identifier = 'cidadequeer'
      name = 'Queer City'
      url = '/cidadequeer/'
      weight = 40
    [[languages.en.menus.main]]
      identifier = 'paim'
      name = 'Paim Street'
      url = '/paim/'
      weight = 50

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
