[build.environment]
DART_SASS_VERSION = "1.93.2"
GO_VERSION = "1.25.3"
HUGO_VERSION = "0.152.2"
NODE_VERSION = "22.20.0"
TZ = "America/Mexico_City"

[build]
  command = "hugo --gc --minify && pnpm dlx pagefind --source public"
  publish = "public"
# publish = "public"
# command = """\
#   git config core.quotepath false && \
#   hugo --gc --minify --baseURL "${URL}"
#   """